Lecture 1/hw
Zimson/rc2023 pull request #1
Opened 2023-11-14 14:56 UTC by Zimson

2023-11-16 09:30 UTC, ArchieSA requested changes

2023-11-16 09:30 UTC, ArchieSA commented on src/main.tsx
> +root.render(
не нашел решение с jsx, доп задание не исключает основное

2023-11-16 10:01 UTC, Zimson commented on src/main.tsx
> +root.render(
@ArchieSA done

2023-11-23 10:56 UTC, SArchieEdu approved these changes

2023-11-23 11:57 UTC, merged